env:
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: 2018
rules:
  "@typescript-eslint/no-parameter-properties": off
  "@typescript-eslint/camelcase":
    - allow: ["client_id", "client_secret"]
